# Generate and publish the static map occupancy grid from the static_costmap image.
# The pixels in the image have values between 0 and 255 with 0 being an obstacle and 255 being free space.
# Then the values are scaled to values between 0 and 100 to create the occupancy grid, where 0 is free space 
# and 100 is occupied space.
# image: static_costmap.png
# resolution: 0.1953125
# origin: [-25.0, -25.0, 0.0]
# occupied_thresh: 0.99
# free_thresh: 0
# negate: 0
# mode: scale