controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    position_controller:
      type: position_controllers/JointGroupPositionController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

position_controller:
  ros__parameters:
    joints:
      - steering1
      - steering2
      - steering3
      - steering4
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

velocity_controller:
  ros__parameters:
    joints:
      - driving1
      - driving2
      - driving3
      - driving4
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

joint_state_broadcaster:
  ros__parameters:
    extra_joints:
      - right_pivot
      - left_pivot
      - chassis_to_caster_axis
      - caster_axis_to_caster_wheel
