local_ekf_filter_node:
  ros__parameters:
    frequency: 25.0
    sensor_timeout: 0.1
    transform_timeout: 0.0
    transform_time_offset: 0.0
    publish_tf: true
    two_d_mode: true
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    use_sim_time: false
    permit_corrected_publication: true
    # reset_on_time_jump: true
    debug: false
    debug_out_file: local_ekf_debug.txt

    #LIORF odometry
    # odom0: /liorf/mapping/odometry
    # odom0_config: [true,  true,  true,      # x, y, z               (position)
    #                true, true, true,        # roll, pitch, yaw      (orientation)
    #                false, false, false,     # vx, vy, vz            (position velocity)
    #                false, false, false,     # vroll, vpitch, vyaw   (rotational velocity)
    #                false, false, false]     # ax, ay, az            (position acceleration)
    # odom0_differential: false
    # odom0_relative: false
    # odom0_queue_size: 10
    # odom0_pose_rejection_threshold: 1.0  #lower this parameter if you want outliers to be aggressively removed. Currently used to filter liorfs output in case the lidar data is blocked
    # odom0_twist_rejection_threshold: 1.0
    # odom0_nodelay: true
    # smooth_lagged_data: true
    # history_length: 1.5

    #IMU output from the madgwick filter with custom covariance values
    # imu0: /imu/modified
    # imu0_config: [false, false, false,     # x, y, z               (position)
    #               false, false, false,      # roll, pitch, yaw      (orientation)
    #               false, false, false,       # vx, vy, vz            (position velocity)
    #               false, false, true,      # vroll, vpitch, vyaw   (rotational velocity)
    #               true, true, false]     # ax, ay, az            (position acceleration)
    # imu0_nodelay: true
    # imu0_queue_size: 2
    # imu0_relative: true
    # imu0_linear_acceleration_rejection_threshold: 2.0
    # imu0_twist_rejection_threshold: 2.0
    # imu0_remove_gravitational_acceleration: true
    # imu0_differential: true

    #Arduino 9-axis IMU : we fuse yaw, ax, ay, gz
    imu0: /imu_nano
    imu0_config: [false, false, false,     # x, y, z               (position)
                  false, false, true,      # roll, pitch, yaw      (orientation)
                  false, false, false,       # vx, vy, vz            (position velocity)
                  false, false, true,      # vroll, vpitch, vyaw   (rotational velocity)
                  true, true, false]     # ax, ay, az            (position acceleration)
    imu0_nodelay: true
    imu0_queue_size: 2
    imu0_relative: true
    imu0_linear_acceleration_rejection_threshold: 2.0
    imu0_twist_rejection_threshold: 2.0
    imu0_remove_gravitational_acceleration: false

    #Wheel Odometry node from wheels_control --> returns 2D speeds and positions of the rover (x, y, yaw, vx, vy, vyaw)
    odom0: /wheel_odom
    odom0_config: [true,  true,  false,      # x, y, z               (position)
                   false, false, false,        # roll, pitch, yaw      (orientation)
                   true, false, false,     # vx, vy, vz            (position velocity)
                   false, false, false,     # vroll, vpitch, vyaw   (rotational velocity)
                   false, false, false]     # ax, ay, az            (position acceleration)
    
    odom0_differential: false
    odom0_relative: true
    odom0_queue_size: 1

# [ADVANCED] The process noise covariance matrix can be difficult to tune, and can vary for each application, so it is
# exposed as a configuration parameter. This matrix represents the noise we add to the total error after each
# prediction step. The better the omnidirectional motion model matches your system, the smaller these values can be.
# However, if users find that a given variable is slow to converge, one approach is to increase the
# process_noise_covariance diagonal value for the variable in question, which will cause the filter's predicted error
# to be larger, which will cause the filter to trust the incoming measurement more during correction. The values are
# ordered as x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az. Defaults to the matrix below if
# unspecified.
    process_noise_covariance: [0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.07, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.1,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.1,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.08,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.08,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.08,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.08,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.08,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.08,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.1,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.08,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.08,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.08]




    initial_estimate_covariance: [1e-5, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                    0.0,  1e-5, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                    0.0,  0.0,  1e-5, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                    0.0,  0.0,  0.0,  1e-5, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                    0.0,  0.0,  0.0,  0.0,  1e-5, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                    0.0,  0.0,  0.0,  0.0,  0.0,  1e-5, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                    0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-5, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                    0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-5, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                    0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-5, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                    0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-5, 0.0,  0.0,  0.0,  0.0,  0.0,
                                    0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-5, 0.0,  0.0,  0.0,  0.0,
                                    0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-5, 0.0,  0.0,  0.0,
                                    0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-5, 0.0,  0.0,
                                    0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-5, 0.0,
                                    0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1e-5]
