<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>path_planning</name>
  <version>0.0.1</version>
  <description>Navigation package that launches nav2, deals with the ERC map render to convert it to a nav2 global costmap and publishes the ERC hardcoded waypoints for the navigation task</description>
  <maintainer email="arno.blan334@gmail.com">Arno Laurie, Netfluxx on GitHub</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>action_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav2_behavior_tree</depend>
  <depend>nav2_msgs</depend>
  <exec_depend>nav2_rotation_shim_controller</exec_depend>
  <exec_depend>wheels_control</exec_depend>
  <exec_depend>gradient_costmap</exec_depend>
  <depend>behaviortree_cpp_v3</depend>
  <depend>pluginlib</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf2_ros</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
