bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    enable_groot_monitoring: True
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 1.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]
    

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10000000000.0
    # Goal checker parameters
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.4
      yaw_goal_tolerance: 0.4
      stateful: True

    # # TEB parameters
    FollowPath:
      plugin: "teb_local_planner/TebLocalPlannerROS"
      footprint_model.type: polygon
      footprint_model.vertices: "[ [-0.7, 0.6], [0.7, 0.6], [0.7, -0.6], [-0.7, -0.6] ]"
      min_obstacle_dist: 0.2 # to tune
      inflation_dist: 0.1
      costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
      costmap_converter_spin_thread: True
      costmap_converter_rate: 15
      enable_homotopy_class_planning: True
      enable_multithreading: True
      optimization_verbose: False
      teb_autoresize: True
      min_samples: 3
      max_samples: 20
      max_global_plan_lookahead_dist: 3.0
      visualize_hc_graph: True
      max_vel_x: 0.4 # 0.26
      max_vel_theta: 0.4
      acc_lim_x: 1.0
      acc_lim_theta: 0.2
      xy_goal_tolerance: 0.5
      yaw_goal_tolerance: 0.5

      weight_optimaltime: 5.0
      weight_inflation: 0.2
      #weight_obstacle:
      #weight_shortest_path: 3.0



    # Regulated Pure Pursuit Controller
    # FollowPath:
    #   plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
    #   desired_linear_vel: 0.5
    #   max_linear_accel: 0.5
    #   max_linear_decel: 0.6
    #   lookahead_dist: 0.6
    #   min_lookahead_dist: 0.3
    #   max_lookahead_dist: 0.9
    #   lookahead_time: 1.5
    #   rotate_to_heading_angular_vel: 1.8
    #   transform_tolerance: 0.1
    #   use_velocity_scaled_lookahead_dist: false
    #   min_approach_linear_velocity: 0.05
    #   use_approach_linear_velocity_scaling: true
    #   max_allowed_time_to_collision: 1.0
    #   use_regulated_linear_velocity_scaling: true
    #   use_cost_regulated_linear_velocity_scaling: false
    #   regulated_linear_scaling_min_radius: 0.9
    #   regulated_linear_scaling_min_speed: 0.25
    #   use_rotate_to_heading: true
    #   rotate_to_heading_min_angle: 0.785
    #   max_angular_accel: 0.4
    #   goal_dist_tol: 0.25
    #   cost_scaling_dist: 0.3
    #   cost_scaling_gain: 1.0
    #   inflation_cost_scaling_factor: 3.0

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False # used to be True

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0 # was 5
      publish_frequency: 10.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: True
      width: 6
      height: 6
      resolution: 0.1
      # robot_radius: 0.05 # 1.0
      footprint: "[ [-0.7, 0.6], [0.7, 0.6], [0.7, -0.6], [-0.7, -0.6] ]"   
      # plugins: ["obstacle_layer", "voxel_layer", "inflation_layer"]
      # plugins: ["inflation_layer","obstacle_layer"]
      plugins: ["obstacle_layer","inflation_layer"]
      lethal_cost_threshold: 70

     
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        combination_method: 1
        inf_is_valid: False
        # observation_sources: pcd not_pcd camera not_camera
        observation_sources:   pcd not_pcd camera not_camera
        # pointcloud:
        #   topic: /ouster/points
        #   sensor_frame: ouster/lidar
        #   data_type: "PointCloud2"
        #   max_obstacle_height: 2.0
        #   min_obstacle_height: 0.4
        #   # raytrace_min_range: 0.0
        #   # raytrace_max_range: 11.0
        #   # obstacle_max_range: 10.0 #100.0
        #   # obstacle_min_range: 1.0
        #   raytrace_range: 11.0
        #   obstacle_range: 10.0
        #   clearing: True
        #   marking: True
        pcd:
          topic: /lidar_filter/filtered_points
          sensor_frame: ouster/lidar
          data_type: "PointCloud2"
          max_obstacle_height: 4.0
          min_obstacle_height: -2.0
          # raytrace_min_range: 0.0
          # raytrace_max_range: 11.0
          # obstacle_max_range: 10.0 #100.0
          obstacle_min_range: 0.0
          # raytrace_range: 11.0
          obstacle_range: 30.0
          clearing: False
          marking: True
        not_pcd:
          topic: /lidar_filter/floor_points
          sensor_frame: ouster/lidar
          data_type: "PointCloud2"
          max_obstacle_height: 4.0
          min_obstacle_height: -2.0
          # raytrace_min_range: 0.0
          # raytrace_max_range: 11.0
          # obstacle_max_range: 10.0 #100.0
          obstacle_min_range: 0.0
          # raytrace_range: 11.0
          obstacle_range: 30.0
          clearing: True
          marking: False
        camera:  # used for detecting obstacles with camera
          topic: /obstacles_points
          sensor_frame: camera_F
          data_type: "PointCloud2"
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0 # 0.15
          clearing: False
          marking: True

        not_camera:  # used for clearing obstacles detected by camera
          topic: /not_obstacles_points
          sensor_frame: camera_F
          data_type: "PointCloud2"
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0 # 0.15
          clearing: True
          marking: False

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.0
        inflation_radius:  1.0

      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 10.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: True
      lethal_cost_threshold: 80
      #origin_x: -3.0
      #origin_y: -20.0
      
      # robot_radius: 0.05
      footprint: "[ [-0.7, 0.6], [0.7, 0.6], [0.7, -0.6], [-0.7, -0.6] ]"  
      resolution: 0.2
      width: 60
      height: 60
      track_unknown_space: true
      plugins: ["obstacle_layer","inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        combination_method: 1
        inf_is_valid: False
        observation_sources:  pcd not_pcd 
        # pointcloud:
        #   topic: /ouster/points
        #   sensor_frame: ouster/lidar
        #   data_type: "PointCloud2"
        #   max_obstacle_height: 3.0
        #   min_obstacle_height: 0.5
        #   # raytrace_min_range: 0.0
        #   # raytrace_max_range: 21.0
        #   # obstacle_max_range: 20.0 #100.0
        #   # obstacle_min_range: 1.0
        #   raytrace_range: 11.0
        #   obstacle_range: 10.0
        #   clearing: True
        #   marking: True
        pcd:
          topic: /lidar_filter/filtered_points
          sensor_frame: ouster/lidar
          data_type: "PointCloud2"
          max_obstacle_height: 4.0
          min_obstacle_height: -2.0
          # raytrace_min_range: 0.0
          # raytrace_max_range: 11.0
          # obstacle_max_range: 10.0 #100.0
          obstacle_min_range: 0.0
          # raytrace_range: 11.0
          obstacle_range: 30.0
          clearing: False
          marking: True
        not_pcd:
          topic: /lidar_filter/floor_points
          sensor_frame: ouster/lidar
          data_type: "PointCloud2"
          max_obstacle_height: 4.0
          min_obstacle_height: -2.0
          # raytrace_min_range: 0.0
          # raytrace_max_range: 11.0
          # obstacle_max_range: 10.0 #100.0
          obstacle_min_range: 0.0
          # raytrace_range: 11.0
          obstacle_range: 30.0
          clearing: True
          marking: False
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.0  # 3.0
        inflation_radius: 1.0 # 0.55
      always_send_full_costmap: True

  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False



waypoint_follower:
  ros__parameters:
    loop_rate: 2
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 0.5



planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 20.0
      use_astar: false
      allow_unknown: true
   
planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "back_up", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    back_up:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: map
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: False
    # simulate_ahead_time: 
    # max_rotational_vel: 10.0
    # min_rotational_vel: -10.0
    # rotational_acc_lim: 10.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: False
